#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
@author: quincy qiang
@contact:1185918903@qq.com
@license: Apache Licence
@time: 2023/11/16 22:45
"""
import torch
nyt_rel_label_map = {
    'ORG': {
        "0": "/business/company/advisors",
        "1": "/business/company/founders",
        "2": "/business/company/industry",
        "3": "/business/company/major_shareholders",
        "4": "/business/company/place_founded",
        "16": "/people/person/ethnicity",  #
        "22": "/sports/sports_team/location",
    },
    'PER': {
        "5": "/business/company_shareholder/major_shareholder_of",
        "6": "/business/person/company",
        "12": "/people/deceased_person/place_of_death",
        "13": "/people/ethnicity/geographic_distribution",
        "14": "/people/ethnicity/people",
        "15": "/people/person/children",
        "17": "/people/person/nationality",
        "18": "/people/person/place_lived",
        "19": "/people/person/place_of_birth",
        "20": "/people/person/profession",
        "21": "/people/person/religion",
    },
    'LOC': {
        "7": "/location/administrative_division/country",
        "8": "/location/country/administrative_divisions",
        "9": "/location/country/capital",
        "10": "/location/location/contains",
        "11": "/location/neighborhood/neighborhood_of",
        "23": "/sports/sports_team_location/teams"
    }
}
webnlg_rel_label_map = {
    'ORG': {
        "0": "/business/company/advisors",
        "1": "/business/company/founders",
        "2": "/business/company/industry",
        "3": "/business/company/major_shareholders",
        "4": "/business/company/place_founded",
        "16": "/people/person/ethnicity",  #
        "22": "/sports/sports_team/location",
    },
    'PER': {
        "18": "almaMater",
        "23": "attackAircraft",
        "25": "award",
        "26": "awards",
        "31": "birthPlace",
        "41": "child",
        "45": "club",
        "57": "deathPlace",
        "64": "doctoralAdvisor",
        "94": "hometown",
        "96": "influencedBy",
        "117": "nationality",
        "121": "notableWork",
        "127": "occupation",
        "139": "placeOfBirth",
        "149": "residence",
        "154": "served as Chief of the Astronaut Office in",
        "155": "significantBuilding",
        "156": "significantProject",
        "163": "title",
        "165": "voice",
        "166": "was a crew member of",
        "168": "was selected by NASA",
    },
    'LOC': {
        "12": "administrativeArrondissement",
        "13": "administrativeCounty",
        "19": "anthem",
        "22": "areaCode",
        "30": "bird",
        "35": "capital",
        "37": "chairman",
        "49": "country",
        "50": "countySeat",
        "54": "currency",
        "59": "demonym",
        "66": "elevationAboveTheSeaLevel",
        "70": "ethnicGroup",
        "71": "ethnicGroups",
        "76": "fossil",
        "80": "gemstone",
        "83": "governingBody",
        "84": "governmentType",
        "86": "has to its north",
        "87": "has to its northeast",
        "88": "has to its northwest",
        "89": "has to its southeast",
        "90": "has to its southwest",
        "91": "has to its west",
        "98": "isPartOf",
        "101": "language",
        "102": "languages",
        "103": "largestCity",
        "104": "leader",
        "105": "leaderName",
        "106": "leaderParty",
        "107": "leaderTitle",
        "110": "location",
        "111": "locationCity",
        "114": "mayor",
        "118": "nearestCity",
        "119": "neighboringMunicipality",
        "128": "officialLanguage",
        "136": "part",
        "137": "partsType",
        "138": "patronSaint",
        "140": "populationTotal",
        "141": "postalCode",
        "146": "regionServed",
        "147": "religion",
        "148": "representative",
        "150": "river",
        "153": "senators",
    },
    "public building": {
        "20": "architect",
        "21": "architecturalStyle",
        "33": "buildingStartDate",
        "34": "buildingType",
        "36": "category",
        "48": "completionDate",
        "55": "currentTenants",
        "58": "dedicatedTo",
        "60": "developer",
        "74": "floorCount",
        "110": "location",
        "116": "municipality",
        "124": "numberOfRooms",
        "133": "owner",
        "134": "owningOrganisation",
        "162": "tenant",
        "170": "yearOfConstruction"
    },
    "Location Organization": {
        "0": "1st_runway_LengthFeet",
        "1": "1st_runway_LengthMetre",
        "2": "1st_runway_Number",
        "3": "1st_runway_SurfaceType",
        "4": "3rd_runway_LengthFeet",
        "5": "4th_runway_LengthFeet",
        "6": "5th_runway_Number",
        "11": "academicStaffSize",
        "14": "affiliation",
        "15": "affiliations",
        "29": "bedCount",
        "37": "chairman",
        "39": "chancellor",
        "40": "chief",
        "42": "city",
        "43": "cityServed",
        "47": "compete in",
        "56": "dean",
        "62": "district",
        "67": "elevationAboveTheSeaLevel_(in_feet)",
        "68": "elevationAboveTheSeaLevel_(in_metres)",
        "69": "established",
        "77": "foundationPlace",
        "78": "foundedBy",
        "92": "headquarter",
        "95": "hubAirport",
        "120": "nickname",
        "123": "numberOfPostgraduateStudents",
        "125": "numberOfStudents",
        "126": "numberOfUndergraduateStudents",
        "129": "operatingOrganisation",
        "132": "outlookRanking",
        "145": "region",
        "135": "parentCompany",
        "143": "president",
        "146": "regionServed",
        "151": "runwayLength",
        "161": "state",
        "167": "was given the 'Technical Campus' status by",
    },
    "Character organization": {
        "16": "aircraftFighter",
        "17": "aircraftHelicopter",
        "27": "backup pilot",
        "28": "battles",
        "38": "champions",
        "46": "commander",
        "53": "crewMembers",
        "79": "founder",
        "85": "ground",
        "93": "headquarters",
        "99": "jurisdiction",
        "100": "keyPerson",
        "108": "league",
        "111": "locationCity",
        "113": "manager",
        "122": "numberOfMembers",
        "130": "operator",
        "133": "owner",
        "152": "season",
        "158": "sportsGoverningBody",
        "164": "transportAircraft",
    },
    "Books and videos": {
        "7": "EISSN_number",
        "8": "LCCN_number",
        "9": "OCLC_number",
        "10": "academicDiscipline",
        "24": "author",
        "32": "broadcastedBy",
        "51": "creator",
        "65": "editor",
        "73": "firstPublicationYear",
        "75": "followedBy",
        "81": "genre",
        "101": "language",
        "109": "literaryGenre",
        "115": "mediaType",
        "142": "precededBy",
        "144": "publisher",
        "160": "starring",

    },
    "vegetable": {
        "52": "creatorOfDish",
        "61": "dishVariation",
        "97": "ingredient",
        "112": "mainIngredients",
        "145": "region",
        "169": "year",
    },
    "Virus": {
        "44": "class",
        "63": "division",
        "72": "family",
        "82": "genus",
        "131": "order",
        "157": "spokenIn",
    }
}



def get_entity_types(pred_rel, dataset_name='nyt'):
    if dataset_name == 'nyt':
        entity_types = torch.zeros((24))
        rel_label_map = nyt_rel_label_map
    else:
        entity_types = torch.zeros((171))
        rel_label_map = webnlg_rel_label_map

    for key, values in rel_label_map.items():
        if str(pred_rel) in values:
            for rel_id, _ in values.items():
                entity_types[rel_id] = 1
    return entity_types
